name: CI Feature to Develop

on:
   push:
       branches:
           - 'feature/**'

jobs:
  job-merge-feature-to-develop:
    name: merge-feature-to-develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Merge main -> feature
        if: ${{ contains(github.event.head_commit.message, 'merge-to-dev') }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: master
          target-branch: ${{ github.ref }}

#      - name: Instalación de librerías y dependencias
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Correr pruebas
#        id: correr-pruebas
#        run: python -m unittest discover -s tests

#      - name: feature -> develop
#        if: ${{ success() && contains(github.event.head_commit.message, 'merge-to-dev') }}
#        uses: tukasz/direct-merge-action@master
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          source-branch: ${{ github.ref }}
#          target-branch: develop



#jobs:
#  job-verificar-commit:
#    name: verificar commit
#    runs-on: ubuntu-latest
#    outputs:
#      mergeToDevelop: ${{ contains(github.event.head_commit.message, 'merge-to-dev') }}
#    steps:
#      - name: check if do merge
#        id: check
#        run: echo ${{ contains(github.event.head_commit.message, 'merge-to-dev') }}
#
#  job-merge-feature-dev:
#    name: merge-dev-feature
#    runs-on: ubuntu-latest
#    steps:
#    - name: Merge feature develop
#      if: ${{need.job-verificar-commit.outputs.mergeToDevelop}}
#      outputs:
#        respuesta: ${{ steps.git-resultado.outputs.respuesta }}
#      uses: tukasz/direct-merge-action@master
#      with:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        source-branch: develop
#        target-branch: ${{ github.ref }}
#    - name: git resultado
#      id: git-resultado
#      if: ${{ success() }}
#      env:
#        MENSAJE_EXITO: True
#      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
#
#  job-ejecutar-pruebas:
#    name: ejecutar-pruebas
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout de repositorio
#      uses: actions/checkout@v2
#    - name: Configuración de entorno de python
#      uses: actions/setup-python@v2
#      with:
#          python-version: '3.7'
#    - name: Instalación de librerías y dependencias
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: ejecutar pruebas
#      id: ejecutar-pruebas
#      run: python -m unittest discover -s tests

#  job-push:
#    name: hacer-merge
